### ISSUE TITLE
upgrade capacitor version to ^3.3.1

### ISSUE THREAD

**Issue by manuongithub** [jepiqueau/react-video-player-hook#1]
will it be possible to upgrade to
"@capacitor/core": "^3.3.1"?

**Comment by manuongithub** [comment]
`npm install --save-dev react-video-player-hook

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: kiddo-book@0.0.1
npm ERR! Found: @capacitor/core@3.3.1
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"^3.3.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^2.4.2" from react-video-player-hook@0.0.4
npm ERR! node_modules/react-video-player-hook
npm ERR!   dev react-video-player-hook@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/manu.mehrotra/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/manu.mehrotra/.npm/_logs/2021-11-08T07_17_43_574Z-debug.log`

**Comment by jepiqueau** [comment]
@manuongithub I will do that later tonight as I am not available before thanks for your patience and thanks for using the plugin

**Comment by jepiqueau** [comment]
@manuongithub This is done

**Comment by manuongithub** [comment]
thanks @jepiqueau , but somehow I get the following now when I try to install it:

` npm install git+ssh://git@github.com:jepiqueau/react-video-player-hook.git
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: kiddo-book@0.0.1
npm ERR! Found: capacitor-video-player@3.2.5
npm ERR! node_modules/capacitor-video-player
npm ERR!   capacitor-video-player@"^3.2.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer capacitor-video-player@"^3.3.0-1" from react-video-player-hook@1.0.0
npm ERR! node_modules/react-video-player-hook
npm ERR!   react-video-player-hook@"git+ssh://git@github.com:jepiqueau/react-video-player-hook.git" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/manu.mehrotra/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/manu.mehrotra/.npm/_logs/2021-11-08T16_28_59_621Z-debug.log`

**Comment by jepiqueau** [comment]
@manuongithub Can you confirm that it is working on your side `npm i --save react-video-player-hook`

**Comment by jepiqueau** [comment]
@manuongithub if I do not get any comments from you I will close the issue
